<?php

namespace AppBundle\Repository;

/**
 * BackgroundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackgroundRepository extends \Doctrine\ORM\EntityRepository
{
}
