<?php

namespace AppBundle\Repository;

/**
 * PoemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSinglePoem(int $id)
    {
        return $this->createQueryBuilder('p')
            ->select('p, b')
            ->join('p.background', 'b')
            ->getQuery()->getOneOrNullResult();
    }
}
