# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        api_key_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api/admin/*
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator




