# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api_key_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: false
            pattern: ^/api/*
            context: api_context
            logout: ~
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator

        api_key_get:
            stateless: false
            context: api_context
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: get_posts

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }




